<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Ventas.Application\Ventas.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.Web\Shared.Web.csproj" />
    <ProjectReference Include="..\..\..\Shared\Common\Common.Web\Common.Web.csproj" />
  </ItemGroup>

</Project>
